version: 2
updates:
- package-ecosystem: gradle
  directory: "/platform"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.flywaydb:flyway-core
    versions:
    - 7.5.3
  - dependency-name: org.testcontainers:postgresql
    versions:
    - 1.15.2
  - dependency-name: org.testcontainers:testcontainers
    versions:
    - 1.15.2
  - dependency-name: org.testcontainers:mysql
    versions:
    - 1.15.2
