---
version: '2.4'

services:

  lb:
    build: ./infrastructure/envoy
    depends_on:
      - account
    ports:
      - 9901:9901
      - 8080:10000
    mem_limit: 32M

  account:
    build: account-service
    ports:
      - 8080
    environment:
      JDBC_URL: jdbc:mysql://database:3306/event_store
      DB_USER: test
      DB_PASSWORD: test
      ZIPKIN_URL: http://zipkin:9411/api/v2/spans
    mem_limit: 128M
    scale: 2

  database:
    image: mysql:8.0.28
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: event_store
    volumes:
      - data:/var/lib/mysql
    mem_limit: 512M

  prometheus:
    image: prom/prometheus:v2.33.4
    ports:
      - 9090:9090
    volumes:
      - ./infrastructure/prometheus/:/etc/prometheus/
    mem_limit: 64M

  grafana:
    image: grafana/grafana:8.4.3
    ports:
      - 3000:3000
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ORG_ROLE: "Editor"
    volumes:
      - ./infrastructure/grafana/provisioning:/etc/grafana/provisioning/
      - ./infrastructure/grafana/dashboards:/var/lib/grafana/dashboards/
    mem_limit: 64M

  zipkin:
    image: openzipkin/zipkin:2.23.16
    ports:
      - 9411:9411
    mem_limit: 512M

volumes:
  data:
    driver_opts:
      type: tmpfs
      device: tmpfs