services:

  lb:
    build: ./infrastructure/envoy
    depends_on:
      - account
    ports:
      - 9901:9901
      - 8080:10000
    labels:
      logging: promtail
      service: envoy
    mem_limit: 32M

  account:
    image: account:snapshot
    ports:
      - 8080
    environment:
      JDBC_URL: jdbc:postgresql://database:5432/event_store
      DB_USER: test
      DB_PASSWORD: test
      OPENTELEMETRY_URL: http://opentelemetry-collector:4318/v1/metrics
      ZIPKIN_URL: http://zipkin:9411/api/v2/spans
    labels:
      logging: promtail
      service: account
    mem_limit: 128M
    deploy:
      replicas: 2

  database:
    image: postgres:16.1
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: event_store
    volumes:
      - data:/var/lib/postgresql/data
    mem_limit: 512M

  promtail:
    image: grafana/promtail:2.9.3
    volumes:
      - ./infrastructure/promtail/promtail.yml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock

  loki:
    image: grafana/loki:2.9.3
    volumes:
      - ./infrastructure/loki/loki.yml:/etc/loki/local-config.yaml
    ports:
      - 3100

  opentelemetry-collector:
    image: otel/opentelemetry-collector-contrib:0.91.0
    volumes:
      - ./infrastructure/opentelemetry-collector/opentelemetry.yml:/etc/otelcol-contrib/config.yaml
    ports:
      - 3500 # Loki ingest port
      - 4318 # OTLP http receiver
      - 9099:9099 # Prometheus scrape endpoint
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 55679:55679 # zpages extension

  prometheus:
    image: prom/prometheus:v2.48.1
    ports:
      - 9090:9090
    volumes:
      - ./infrastructure/prometheus/:/etc/prometheus/
    mem_limit: 64M

  grafana:
    image: grafana/grafana:10.2.3
    ports:
      - 3000:3000
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ORG_ROLE: "Editor"
    volumes:
      - ./infrastructure/grafana/provisioning:/etc/grafana/provisioning/
      - ./infrastructure/grafana/dashboards:/var/lib/grafana/dashboards/
    mem_limit: 64M

  zipkin:
    image: openzipkin/zipkin:2.26.0
    ports:
      - 9411:9411
    mem_limit: 512M

volumes:
  data:
    driver_opts:
      type: tmpfs
      device: tmpfs