services:

  lb:
    build: ./infrastructure/envoy
    depends_on:
      - account
    ports:
      - 9901:9901
      - 8080:10000
    mem_limit: 32M

  account:
    image: account:snapshot
    ports:
      - 8080
    environment:
      JDBC_URL: jdbc:postgresql://database:5432/event_store
      DB_USER: test
      DB_PASSWORD: test
      OTEL_EXPORTER_OTLP_ENDPOINT: http://opentelemetry-collector:4317
    mem_limit: 128M
    deploy:
      replicas: 2

  database:
    image: postgres:17.6
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: event_store
    volumes:
      - data:/var/lib/postgresql/data
    mem_limit: 512M

  loki:
    image: grafana/loki:3.5.4
    volumes:
      - ./infrastructure/loki/loki.yml:/etc/loki/local-config.yaml
    ports:
      - 3100
    mem_limit: 512M

  opentelemetry-collector:
    image: otel/opentelemetry-collector-contrib:0.135.0
    volumes:
      - ./infrastructure/opentelemetry-collector/opentelemetry.yml:/etc/otelcol-contrib/config.yaml
    ports:
      - 4317 # OTLP grpc receiver
      - 9099 # Prometheus scrape endpoint
    mem_limit: 512M

  prometheus:
    image: prom/prometheus:v3.5.0
    command: [ "--web.enable-remote-write-receiver", "--enable-feature=exemplar-storage", "--config.file=/etc/prometheus/prometheus.yml" ]
    ports:
      - 9090:9090
    volumes:
      - ./infrastructure/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    mem_limit: 64M

  tempo:
    image: grafana/tempo:2.8.2
    command: [ "-config.file=/etc/tempo.yml" ]
    volumes:
      - ./infrastructure/tempo/tempo.yml:/etc/tempo.yml
    ports:
      - 3200
      - 4318  # otlp http
    mem_limit: 128M

  grafana:
    image: grafana/grafana:12.1.1
    ports:
      - 3000:3000
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_FEATURE_TOGGLES_ENABLE: "traceqlEditor traceQLStreaming metricsSummary"
    volumes:
      - ./infrastructure/grafana/provisioning:/etc/grafana/provisioning/
      - ./infrastructure/grafana/dashboards:/var/lib/grafana/dashboards/
    mem_limit: 64M

volumes:
  data:
    driver_opts:
      type: tmpfs
      device: tmpfs