---
version: '3.7'

services:

  #lb:
  #  build: src/test/resources/load-balancer
  #  depends_on:
  #    - accounts-1
  #    - accounts-2
  #  ports:
  #    - 8080:80

  lb-envoy:
    build: src/test/resources/envoy
    depends_on:
      - accounts-1
      - accounts-2
    ports:
      - 9901
      - 8080:10000

  accounts-1:
    build: .
    ports:
      - 8080
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_JDBC_URL: jdbc:mysql://database:3306/event_store

  accounts-2:
    build: .
    ports:
      - 8080
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_JDBC_URL: jdbc:mysql://database:3306/event_store

  database:
    image: mysql:8.0.18
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: event_store
    volumes:
      - data:/var/lib/mysql

  prometheus:
    image: prom/prometheus:v2.11.1
    ports:
      - 9090:9090
    volumes:
      - ./src/test/resources/prometheus/:/etc/prometheus/

  grafana:
    image: grafana/grafana:6.2.5
    ports:
      - 3000:3000
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ORG_ROLE: "Editor"
    volumes:
      - ./src/test/resources/grafana/provisioning:/etc/grafana/provisioning/
      - ./src/test/resources/grafana/dashboards:/var/lib/grafana/dashboards/

volumes:
  data:
    driver_opts:
      type: tmpfs
      device: tmpfs