---
version: '2.4'

services:

  lb:
    build: src/test/resources/envoy
    depends_on:
      - account
    ports:
      - 9901
      - 10000

  account:
    build: .
    ports:
      - 8080
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_JDBC_URL: jdbc:mysql://database:3306/event_store
    scale: 2

  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: event_store
    volumes:
      - data:/var/lib/mysql

volumes:
  data:
    driver_opts:
      type: tmpfs
      device: tmpfs