apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
    editable: true
    uid: prometheus
    jsonData:
      exemplarTraceIdDestinations:
        - datasourceUid: tempo
          name: traceID

  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    isDefault: false
    editable: true
    uid: loki

  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    isDefault: false
    editable: true
    uid: tempo
    jsonData:
      tracesToLogsV2:
        datasourceUid: 'loki'
        customQuery: true
        query: '{exporter="OTLP"} |= "$${__trace.traceId}"'
        spanStartTimeShift: '-5m'
        spanEndTimeShift: '5m'
      tracesToMetrics:
        datasourceUid: 'prometheus'
        spanStartTimeShift: '-5m'
        spanEndTimeShift: '5m'
      #  tags: [ { key: 'service.name', value: 'service' }, { key: 'job' } ]
      #  queries:
      #    - name: 'Sample query'
      #      query: 'sum(rate(traces_spanmetrics_latency_bucket{$$__tags}[5m]))'
      serviceMap:
        datasourceUid: 'prometheus'
      nodeGraph:
        enabled: true
      #search:
      #  hide: false
      lokiSearch:
        datasourceUid: 'loki'
      #traceQuery:
      #  timeShiftEnabled: true
      #  spanStartTimeShift: '1h'
      #  spanEndTimeShift: '-1h'
      #spanBar:
      #  type: 'Tag'
      #  tag: 'http.path'
