receivers:
  otlp:
    protocols:
      http:
  loki:
    protocols:
      http:
    use_incoming_timestamp: true
  zipkin:

processors:
  batch:
  attributes:
    actions:
      - action: insert
        key: loki.attribute.labels
        value: service
      - action: insert
        key: loki.format
        value: raw

exporters:
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
  prometheus:
    endpoint: 0.0.0.0:9099
    send_timestamps: true
    metric_expiration: 180m
    enable_open_metrics: true
    add_metric_suffixes: false
    resource_to_telemetry_conversion:
      enabled: true
  otlphttp/tempo:
    endpoint: http://tempo:4318

service:
  pipelines:
    logs:
      receivers: [loki]
      processors: [attributes, batch]
      exporters: [loki]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    traces:
      receivers: [zipkin]
      processors: [batch]
      exporters: [otlphttp/tempo]
