receivers:
  otlp:
    protocols:
      grpc:

processors:
  memory_limiter: # https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor/memorylimiterprocessor
    check_interval: 1s
    limit_percentage: 80
    spike_limit_percentage: 40
  batch: # https://github.com/open-telemetry/opentelemetry-collector/blob/main/processor/batchprocessor
  attributes:
    actions:
      - action: insert
        key: loki.attribute.labels
        value: service.name,level
      - action: insert
        key: loki.resource.labels
        value: service.name

exporters:
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
  prometheus:
    endpoint: 0.0.0.0:9099
    send_timestamps: true
    metric_expiration: 180m
    enable_open_metrics: true
    add_metric_suffixes: false
    resource_to_telemetry_conversion:
      enabled: true
  otlphttp/tempo:
    endpoint: http://tempo:4318

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [memory_limiter, attributes, batch]
      exporters: [loki]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlphttp/tempo]
