---
version: '2.4'

services:

  lb:
    build: ../../../../infrastructure/envoy
    depends_on:
      - account
    ports:
      - 9901
      - 10000
    mem_limit: 32M

  account:
    build: ../../..
    ports:
      - 8080
    environment:
      JDBC_URL: jdbc:postgresql://database:5432/event_store
      DB_USER: test
      DB_PASSWORD: test
    mem_limit: 128M
    scale: 2

  database:
    image: postgres:14.0
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: event_store
    volumes:
      - data:/var/lib/postgresql/data
    mem_limit: 512M

volumes:
  data:
    driver_opts:
      type: tmpfs
      device: tmpfs