scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9099']

  - job_name: 'envoy'
    metrics_path: '/stats'
    params:
      format: ['prometheus']
    scrape_interval: 5s
    static_configs:
      - targets: ['lb:9901']

  - job_name: 'java-services'
    metrics_path: '/metrics'
    scrape_interval: 5s
    dns_sd_configs:
      - names:
          - opentelemetry-collector
        type: 'A'
        port: 9099
    relabel_configs:
      - source_labels: ['__meta_dns_name']
        target_label: application