admin:
  access_log_path: /dev/stdout
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

node:
  id: default-node
  cluster: api-gateway
  locality:
    zone: default-zone

static_resources:
  listeners:
    - name: service_listener
      address:
        socket_address: { address: 0.0.0.0, port_value: 10000 }
      traffic_direction: OUTBOUND
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                generate_request_id: true
                access_log:
                  - name: envoy.access_loggers.file
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                      path: /dev/stdout
                      typed_json_format:
                        timestamp: "%START_TIME%"
                        protocol: "%PROTOCOL%"
                        request: "%REQ(:METHOD)% %REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%"
                        traceparent: "%REQ(TRACEPARENT)%"
                        duration: "%DURATION%"
                        bytesReceived: "%BYTES_RECEIVED%"
                        upstreamCluster: "%UPSTREAM_CLUSTER%"
                        responseCode: "%RESPONSE_CODE%"
                        bytesSent: "%BYTES_SENT%"
                tracing:
                  provider:
                    name: envoy.tracers.opentelemetry
                    typed_config:
                      "@type": type.googleapis.com/envoy.config.trace.v3.OpenTelemetryConfig
                      service_name: api-gateway
                      grpc_service:
                        envoy_grpc:
                          cluster_name: otel
                        timeout: 0.250s
                  random_sampling:
                    value: 1
                stat_prefix: ingress_http
                codec_type: auto
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: account
                      domains: ["*"]
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: account
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

  clusters:
    - name: account
      connect_timeout: 0.25s
      type: strict_dns
      lb_policy: round_robin
      load_assignment:
        cluster_name: account
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: account
                      port_value: 8080

    - name: otel
      connect_timeout: 1s
      type: strict_dns
      lb_policy: round_robin
      typed_extension_protocol_options:
        envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
          "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
          explicit_http_config:
            http2_protocol_options: {}
      load_assignment:
        cluster_name: otel
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: opentelemetry-collector
                      port_value: 4317
