---
version: '2.4'

services:

  lb:
    build: ../../../infrastructure/envoy
    depends_on:
      - account
    ports:
      - 9901
      - 10000
    mem_limit: 32M

  account:
    build: ../../..
    ports:
      - 8080
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_JDBC_URL: jdbc:mysql://database:3306/event_store
    mem_limit: 128M
    scale: 2

  database:
    image: mysql:8.0.18 # 8.0.19 seems not to work with standalond JVM for some reason
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: event_store
    volumes:
      - data:/var/lib/mysql
    mem_limit: 512M

volumes:
  data:
    driver_opts:
      type: tmpfs
      device: tmpfs