{
 "title": "Account",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Open Account",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": " histogram_quantile(0.99, sum(rate(api_operation_bucket{operation=\"open_account\"}[1m])) by (le, service_name))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": " histogram_quantile(0.95, sum(rate(api_operation_bucket{operation=\"open_account\"}[1m])) by (le, service_name))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": " histogram_quantile(0.90, sum(rate(api_operation_bucket{operation=\"open_account\"}[1m])) by (le, service_name))",
     "legendFormat": "90th percentile"
    }
   ]
  },
  {
   "title": "Query Account",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": " histogram_quantile(0.99, sum(rate(api_operation_bucket{operation=\"query_account\"}[1m])) by (le, service_name))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": " histogram_quantile(0.95, sum(rate(api_operation_bucket{operation=\"query_account\"}[1m])) by (le, service_name))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": " histogram_quantile(0.90, sum(rate(api_operation_bucket{operation=\"query_account\"}[1m])) by (le, service_name))",
     "legendFormat": "90th percentile"
    }
   ]
  },
  {
   "title": "Query Account Events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": " histogram_quantile(0.99, sum(rate(api_operation_bucket{operation=\"query_account_events\"}[1m])) by (le, service_name))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": " histogram_quantile(0.95, sum(rate(api_operation_bucket{operation=\"query_account_events\"}[1m])) by (le, service_name))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": " histogram_quantile(0.90, sum(rate(api_operation_bucket{operation=\"query_account_events\"}[1m])) by (le, service_name))",
     "legendFormat": "90th percentile"
    }
   ]
  },
  {
   "title": "Deposit",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": " histogram_quantile(0.99, sum(rate(api_operation_bucket{operation=\"deposit\"}[1m])) by (le, service_name))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": " histogram_quantile(0.95, sum(rate(api_operation_bucket{operation=\"deposit\"}[1m])) by (le, service_name))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": " histogram_quantile(0.90, sum(rate(api_operation_bucket{operation=\"deposit\"}[1m])) by (le, service_name))",
     "legendFormat": "90th percentile"
    }
   ]
  },
  {
   "title": "Withdraw",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": " histogram_quantile(0.99, sum(rate(api_operation_bucket{operation=\"withdraw\"}[1m])) by (le, service_name))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": " histogram_quantile(0.95, sum(rate(api_operation_bucket{operation=\"withdraw\"}[1m])) by (le, service_name))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": " histogram_quantile(0.90, sum(rate(api_operation_bucket{operation=\"withdraw\"}[1m])) by (le, service_name))",
     "legendFormat": "90th percentile"
    }
   ]
  },
  {
   "title": "Transfer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": " histogram_quantile(0.99, sum(rate(api_operation_bucket{operation=\"transfer\"}[1m])) by (le, service_name))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": " histogram_quantile(0.95, sum(rate(api_operation_bucket{operation=\"transfer\"}[1m])) by (le, service_name))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": " histogram_quantile(0.90, sum(rate(api_operation_bucket{operation=\"transfer\"}[1m])) by (le, service_name))",
     "legendFormat": "90th percentile"
    }
   ]
  },
  {
   "title": "Close Account",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": " histogram_quantile(0.99, sum(rate(api_operation_bucket{operation=\"close_account\"}[1m])) by (le, service_name))",
     "legendFormat": "99th percentile"
    },
    {
     "expr": " histogram_quantile(0.95, sum(rate(api_operation_bucket{operation=\"close_account\"}[1m])) by (le, service_name))",
     "legendFormat": "95th percentile"
    },
    {
     "expr": " histogram_quantile(0.90, sum(rate(api_operation_bucket{operation=\"close_account\"}[1m])) by (le, service_name))",
     "legendFormat": "90th percentile"
    }
   ]
  }
 ]
}