name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14.0.0
    - name: Build
      run: ./gradlew build --parallel --stacktrace
    - name: Upload code coverage report to codeclimate
      uses: paambaati/codeclimate-action@v2.5.6
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        JACOCO_SOURCE_PATH: src/main/java
      with:
        coverageCommand: ./gradlew jacocoTestReport
        coverageLocations: "${{github.workspace}}/build/reports/jacoco/test/jacocoTestReport.xml:jacoco"
    - name: Prepare Release
      id: release_config
      if: ${{ github.ref == 'refs/heads/master' }}
      run: |
        echo "::set-output name=version::$(infrastructure/next-version.sh)"
        git fetch --unshallow
        changes="$(infrastructure/changes-since-last-release.sh)"
        echo $changes
        changes="${changes//'%'/'%25'}"
        changes="${changes//$'\n'/'%0A'}"
        changes="${changes//$'\r'/'%0D'}"
        echo $changes
        echo "::set-output name=changes::$changes"
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      if: ${{ github.ref == 'refs/heads/master' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.release_config.outputs.version }}
        release_name: ${{ steps.release_config.outputs.version }}
        body: |
          ${{ steps.release_config.outputs.changes }}
        draft: false
    - name: Publish docker image
      uses: docker/build-push-action@v1
      if: ${{ github.ref == 'refs/heads/master' }}
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        repository: rieske/account
        tags: ${{ steps.release_config.outputs.version }}
        tag_with_ref: true
        add_git_labels: true
        push: true